---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[rackspace_apt]
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
#- name: centos-6.4
#    run_list:
#      - recipe[rackspace_apt]
#- name: debian-7.2.0
#    run_list:
#      - recipe[rackspace_apt]
#  driver_config:
#    box: opscode-debian-7.2.0
#    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
#
suites:
  - name: default
    run_list:
      - recipe[blogging::default]
    attributes:
      rackspace_mysql:
        server_debian_password: 'TestDebianPassword'
        server_root_password: 'TestRootPassword'
        server_repl_password: 'TestReplicationPassword'
